### PR TITLE
LRDOCS-5115 LPS-77668 javadoc review

### PR DESCRIPTION
**Pull request by mwilliams2014**
cc @jbalsas

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @codyhoag, please, send this back to me whenever you're done with it.

@mwilliams2014, I think you did a wrong rebase here. We should not be seeing the merge commits here.

**Comment by codyhoag** [comment]
@jbalsas sure thing. I'll have it back to you today.

**Comment by codyhoag** [comment]
Sent jbalsas#1150. Thanks!

**Comment by mwilliams2014** [comment]
@jbalsas, I merged the pr you sent me then added my changes on top of that. That's the  merge commit.

**Comment by jbalsas** [comment]
Merge commits aren't allowed in the liferay-portal repo, always rebase :)

**Comment by mwilliams2014** [comment]
Ah, I wasn't aware of that. I'll update it. Thanks!

**Comment by jbalsas** [comment]
No worries, cody already took care of it, I'm working on the final PR!

**Comment by mwilliams2014** [comment]
Yep, I saw that. Thanks @codyhoag !

**Pull request closed without merging**
