### PR TITLE
LPS-51936 Javadoc

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey @codyhoag 

I'm not sure if you're still the person to send javadoc? Otherwise, can you please fwd this to Rich since he's our contact person for Collab&DL

Thanks!

### CODE REVIEW

**Comment by codyhoag** [comment]
Hey Sergio,

Sending javadoc to @jhinkey or I is fine for Collab&DM. We'll get this reviewed soon. Thanks!

**Comment by jhinkey** [comment]
Reviewing now, working in https://github.com/jhinkey/liferay-portal/tree/codyhoag-pr26-LPS-51936_Javadoc

**Comment by jhinkey** [comment]
I sent https://github.com/brianchandotcom/liferay-portal/pull/24732.

**Comment by jhinkey** [comment]
@codyhoag , this PR can be closed. thanks.

**Comment by sergiogonzalez** [comment]
Thanks @jhinkey !

**Pull request closed without merging**
