### PR TITLE
LPS-51530 Javadoc

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Same as https://github.com/codyhoag/liferay-portal/pull/26 but for a different feature.

Thanks! :)

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz

**Comment by jhinkey** [comment]
Reviewing now, thanks.

**Comment by jhinkey** [comment]
Sent https://github.com/brianchandotcom/liferay-portal/pull/24733

**Comment by jhinkey** [comment]
Thanks. This can be closed now.

**Comment by sergiogonzalez** [comment]
Thanks @jhinkey !

**Pull request closed without merging**
